# MRI

## MRI Study Material List

**_Acroyms:_**

```
NMR = Nuclear Magnetic Resonance
MRI = Magnetic Resonance Imaging
MRS = Magnetic Resonance Spectroscopy
```

## Selected Books for MRI & NMR

***Magnetic Resonance Imaging: Physical Principles and Sequence Design***

[Book](https://onlinelibrary.wiley.com/doi/book/10.1002/9781118633953) ```RW Brown, YCN Cheng, EM Haacke, MR Thompson, R Venkatesan```

  - Excellent text that balances mathematical strictness and physics concepts with intuitional and technical explanations. Specific topics, such as fast spin echo, are treated to a lesser extent than desirable; only a few pages about MR spectroscopy

***Handbook of MRI Pulse Sequences*** 

[Book](https://www.sciencedirect.com/book/9780120928613/handbook-of-mri-pulse-sequences) ```MA Bernstein, KF King and XJ Zhou```

 - Outstanding coverage of MR imaging pulse sequences and their various elements, such as radiofrequency (RF) pulses and gradients

***MRI from Proton to Picture***

[Book](https://www.cambridge.org/core/books/mri-from-picture-to-proton/3ADC814FF8FC6A78A54D37746F806D5A) ```DW McRobbie, EA Moore, MJ Graves, MR Prince```

  - Comprehensive introduction to the basics of MR practice and theory; very comprehendible and with superb illustrations; one chapter about MR spectroscopy

***Magnetic Resonance Imaging: Theory and Practice***  

[Book](https://www.amazon.com/Magnetic-Resonance-Imaging-Theory-Practice/dp/3642078230) ```MT Vlaardingerbroek, JA den Boer```

  - Very good book, though not thought for someone, who makes his/her first acquaintance with MRI (as is also stated in its preface; some common nomenclature with Haacke's book)

***MRI: The Basics***

[Book](https://www.amazon.com/MRI-Ray-Hashman-Hashemi-PhD/dp/1608311155) ```RH Hashemi, WG Bradley, CJ Lisanti```

  - Very introductory text that summarizes most important concepts of MRI; a suitable tool to obtain a first overview of MRI principles, but does not provide in-depth insight

***Magnetic Resonance Imaging: Physical Principles and Applications***

[Book](https://www.amazon.com/Magnetic-Resonance-Imaging-Principles-Applications/dp/0123886651) ```V Kuperman```

***NMR Imaging in Biomedicine***

[Book](https://books.google.ae/books/about/NMR_Imaging_in_Biomedicine.html?id=QLBqAAAAMAAJ&redir_esc=y) ```PG Morris, P Mansfield```

  - Classic textbook with elegant treatment of NMR techniques, though too involved for a beginner.

***The Principles of Nuclear Magnetism***

[Book](https://books.google.ae/books?id=9M8U_JK7K54C&printsec=frontcover&dq=The+Principles+of+Nuclear+Magnetism+english!&hl=en&sa=X&ved=2ahUKEwiarMPppKj3AhVARPEDHRYjCf4Q6AF6BAgJEAI#v=onepage&q&f=false) ```A Abragam```

  - Standard text for quantum mechanical treatment of nuclear magnetism; requires good knowledge of quantum mechanics

## Selected Papers

- One of the first papers about the basic concepts of NMR: ```F Bloch, Nuclear induction``` <sup>1

- A good introduction to basic NMR signal detection: ```WS Hinshaw and AH Lent, An introduction to NMR imaging: From the Bloch equation to the imaging equation``` <sup>2

- The fundamental concept of an echo is introduced in: ```EL Hahn, Spin Echoes``` <sup>3

- Basic k-space concepts are discussed in: ```DB Twieg, The k-trajectory formulation of the NMR imaging process with applications in analysis and synthesis of imaging methods``` <sup>4

- The alternate phase encoding scheme for Fourier imaging was introduced in: ```A Kumar, D Welti, and RR Ernst, NMR Fourier Zeugmatography``` <sup>5

- A theory of small tip-angle approximation of viewing slice selection in k-space was developed in: ```J Pauly, D Nishimura, and A Macovski, A k-space analysis of small tip angle excitation``` <sup>6

- Superb and detailed review of the fast spin echo (FSE) sequence together with an introduction to MRI: ```J Listerud, S Einstein, E Outwater, and HY Kressel, First principles of fast spin echo``` <sup>7

- Fast gradient echo imaging is discussed in: ```P van der Meulen, JP Groen, and JJ Cuppen, Very fast MR imaging by field echoes and small angle excitation``` <sup>8

- Overview of contrast and resolution in MRI: ```RT Constable and RM Henkelman, Contrast, resolution, and detectability in MR imaging``` <sup>9

_References_

1. F. Bloch, “Nuclear induction,” Physical Review, vol. 70, pp. 460-74, 1946.
2. W. S. Hinshaw and A. H. Lent, “An introduction to NMR imaging: From the Bloch equation to the imaging equation,” Proceedings of the IEEE, vol. 71, pp. 338-50, 1982.
3. E. L. Hahn, “Spin Echoes,” Physical Review, vol. 80, pp. 580, 1950.
4. D. B. Twieg, “The k-trajectory formulation of the NMR imaging process with applications in analysis and synthesis of imaging methods,” Medical Physics, vol. 10, pp. 610-21, 1983.
5. A. Kumar, D. Welti, and R. R. Ernst, “NMR Fourier Zeugmatography,” Journal of Magnetic Resonance, vol. 18, pp. 69-83, 1975.
6. J. Pauly, D. Nishimura, and A. Macovski, “A k-space analysis of small tip angle excitation,” Journal of Magnetic Resonance, vol. 81, pp. 43-56, 1989.
7. J. Listerud, S. Einstein, E. Outwater, and H. Y. Kressel, “First principles of fast spin echo,” Magnetic Resonance Quarterly, vol. 8, pp. 199-244, 1992
8. P. van der Meulen, J. P. Groen, and J. J. Cuppen, “Very fast MR imaging by field echoes and small angle excitation,” Magnetic Resonance Imaging, vol. 3, pp. 297-9, 1985.
9. R. T. Constable and R. M. Henkelman, “Contrast, resolution, and detectability in MR imaging,” Journal of Computer Assisted Tomography, vol. 15, pp. 297-303, 1991.

## Web links

**Here are some web links that lead to tutorials or introductory material for MRI & MRS:**


- ```The Basics of NMR``` by Hornak with animations, intended for beginners. [Online book](https://www.cis.rit.edu/htbooks/nmr/)

- ```The Basics of MRI``` by Hornak with nice animations, intended for beginners. [Online book](https://www.cis.rit.edu/htbooks/mri/)

- ```Introduction to MRI``` [Link](http://www.mritutor.org/mritutor)

- ```MRI Physics``` put simply; some links to educational topics about MRI, e.g. MRI basics text [Link](http://www.simplyphysics.com/)





