# MRS and NMR Glossary 

***Target Audience:*** Students and researchers who have taken a college or university-level chemistry course 

## Introduction and Fundamentals

```***Energy Splitting:*** ``` The spin states of nuclei have different energy levels when the nucleus is in an external magnetic field (i.e., B0). The difference between energy levels is known as energy (or Zeeman) splitting. This energy difference is what is detected in the NMR experiment using an RF pulse with the same amount of energy.

```***Gyromagnetic Ratio:***``` The ratio of the magnetic moment to the angular momentum of a particl is called gyromagnetic ratio (γ). Usually is expressed in MHz/T, for example the gyromagnetic ratio of 1H nucleus is 42.58MHz/T. Nuclei with a higher gyromagnetic ratio respond more strongly to the external magnetic field, and are generally better for NMR experiments.

```***Isotope:***``` Different forms of the same element that contain equal numbers of protons but different numbers of neutrons in the nucleus. Some nuclei are detectable with NMR (e.g. 13C), some are radioactive (e.g. 11C), while others are neither (e.g. 12C).

```***Larmor Frequency:***``` The characteristic frequency of a nucleus in an external field is referred to as the Larmor frequency, sometimes referred to as the ‘precessional frequency.’ During the NMR experiment, the external field (B1) must match or be very close to the Larmor frequency. This condition is known as ‘resonance.’ The equation that relates the Larmor frequency to the external magnetic field is known as the Larmor equation,  and is the central equation for NMR.

```***Nuclear Spin:***``` Nuclear spin is a property of nuclei that defines its angular momentum. A nucleus must have non-zero spin to be detected in an NMR experiment. 

```***Nuclear Magnetic Resonance (NMR):***``` NMR is a form of spectroscopy that measures the energy of nuclear spins. ‘Nuclear’ refers to the fact we are interested in the atom’s nucleus (protons + neutrons only). ‘Magnetic’ refers to the energy (magnetic field) we are using for the experiment. There is both a strong magnetic field (B0) and a weak magnetic field (B1). The weak field is also referred to as the RF (radiofrequency) field. Finally, the B1 field must be have the same energy or be on ‘resonance’ with the energy of the nuclear spin for the experiment to be successful. 

```***Nucleus:***``` A nucleus contains the protons and neutrons in an atom. The nucleus (or energy of the nucleus) is what is detected in an NMR experiment.

```***Magnetic Resonance Spectroscopy (MRS):***``` MRS uses the same principles of NMR but also includes localization, i.e., the spectrum can be acquired from a specific location in the body or in a sample. The term ‘nuclear’ was removed for use in the clinical setting to avoid confusion with nuclear imaging methods that produce ionizing radiation.  

```***Shielding:***``` The electron density surrounding an atom causes local perturbations in the magnetic field that the nucleus experiences. The effect of causing these perturbations and changing the effective magnetic field experienced by the nucleus is called shielding. The result is an upfield or downfield shift (see Upfield/Downfield) of the resonance frequency. Shielding allows for detection of the same nucleus (e.g., hydrogen nucleus) in different molecules.

```***Spin up/ spin down:***``` When placed in a magnetic field, nuclei that exhibit magnetism can have multiple spin states. For a nucleus with ½ spin, such as hydrogen, there are two states, up or down. The spin-up state is in alignment with the main magnetic field. The spin-down state is in the opposite direction of the magnetic field. 

## NMR Signal and Spectra

```***Baseline:***``` In spectroscopy, baseline refers to a broad signal offset. The baseline must be accounted for in order to accurately quantify the metabolites in the data, and is often subtracted to make the spectrum appear flat. There are many approaches for dealing with baselines. Some techniques use tailored smoothing protocols while others might use Coiflet wavelets, p-splines, or basis lines, whether simulated or acquired. Each approach has pros and cons and these can change with each type of data. It should noted some spectroscopists include macromolecular baseline and lipid signals in their definition of the baseline while other spectroscopists model these two signals separately. There is no consensus regarding these approaches.

```***Chemical Shift:***``` The chemical shift, in ppm, is usually the x-axis in an NMR spectrum. Nuclei in different molecules or at different positions in the same molecule emit slightly distinguishable frequencies after excitation. These frequency differences are called chemical shifts and are measured relative to the frequency of a reference standard. Often the position and number of chemical shifts are diagnostic of the structure of a molecule.

```***Complex Data:***``` FIDs or NMR signals are measured as complex signals. This means that they have both a real and imaginary component. These two components provide complementary information. Phase offsets cycle portions of the signal from the real to the imaginary component. Therefore, raw complex data must be phase corrected so that it is in a standardized form and ready for post-processing and analysis.

```***Imaginary Component:***``` This is called the imaginary component because it is represented by imaginary numbers. The peaks in this component are wider than in the real spectrum and have significant positive and negative components. After correcting the phase of the spectra, the imaginary component was typically discarded. Modern approaches still focus on the real component, but current techniques and research also include the imaginary component in processing and analysis steps.

```***J-coupling:***``` J-coupling (also called spin-spin coupling) is mediated through the electrons that connect coupled spins. It is an indirect interaction between two nuclear spins that arises from hyperfine interactions between the nuclei and local electrons. J-coupling results in peak ‘splitting’ where one peak will be split into 2+ peaks.

```***Magnitude Spectrum:***``` The absolute value of a complex number is called its magnitude. It is calculated by taking the square root of the sum of the squares of the real and imaginary components. While the magnitude spectrum is less informative than the complex spectra, it is helpful because it eliminates the need for imaginary numbers and is unaffected by the phase.

```***Noise:***``` Noise is present in every measured signal. In general, noise is often normally distributed, i.e., comes from a Gaussian distribution, and can be thought of as being overlaid on top of the data. Past certain thresholds, noise will blur or obfuscate the underlying data making it unreliable. Noise can come from many sources including hardware and the environment.

```***Parts Per Million (PPM):***``` PPM is the unit used to plot spectra in the frequency domain, i.e., the x-axis units. Because the resonant frequencies are dependent upon the B0 magnetic field strength, it is difficult to compare spectra from 1.5T, 3T, and 7T scanners. Therefore, they are plotted according to the ppm which is agnostic to the magnetic field strength. The ‘parts per million’ unit comes from frequencies (in Hz) that are normalized by the field strength (in MHz), so the final unit is in 1E10-6 (or 1 part per million). *Note: conventionally, spectra are plotted such that the ppm decreases from left to right.

```***Peak:***``` A peak is a part of the spectra (in the frequency domain) indicating the presence and relative amount of a metabolite. The shape of the peak is most accurately described by the Voigt line shape model (see Voigt lineshape and lineshapes).

```Point Spread Function (PSF):``` This describes the response of an imaging system that is elicited by a point source. The PSF is also known as the impulse response. Narrow PSFs correspond to higher spatial resolution and less blurring.

```Real Component:``` Traditionally, the real component was the only component used for analysis. In “pure absorption” mode, the peak height and peak area correlate with the concentration of the given species. This mode is characterized by peaks reaching their maximum height and their narrowest width.

```Signal-to-Noise Ratio (SNR):``` The signal-to-noise ratio indicates the relative amount of signal, when accounting for noise, and is often used as a data quality metric. In spectroscopy, this is typically calculated by dividing the maximum value of the spectrum (e.g., the largest peak in the frequency domain) by the standard deviation of a portion of the spectrum that contains only noise. 

```Spectrum/Spectra:``` An NMR spectrum (plural: spectra) is the output of performing the Fourier transform on the signal collected in the time domain (i.e., the free induction decay (FID)). It is a one-dimentional signal that contains information about the resonance frequencies from the sample being investigated. Each species, molecule, or metabolite in the sample will produce a peak at a specific frequency. The amplitude of the peak indicates the amount of the species, e.g., in proton spectra, the height of the peak is relative to the number of protons the metabolite has. Similarly, the area under the curve indicates the concentration. For example, brain spectra have a large water peak present at ~4.68 ppm. Compared to this water peak, the metabolite peaks are significantly smaller because their concentration is so much less than that of water.

```Upfield/Downfiled:```  The terms describe the location of a peak in relation to a peak of reference. Upfield refers to the right (lower frequency); downfield refers to the left (higher frequency). Note: these are historical terms that are not as common in modern NMR. 

## NMR Experiment and Hardware

```Adiabatic Pulse:``` An adiabatic pulse creates a more uniform flip angle distribution over the wide range of B1 field strengths. The pulse utilizes lower power and therefore longer pulse durations are needed in order to obtain the same flip angle. The term adiabatic comes from the fact that the direction of the effective field changes slowly with respect to its strength. Their advantage is that the magnetization can be turned completely independently of the strength of B1 field and thus independent of inhomogeneity of the B1 field.

```B0:``` The main magnetic field of an MR system. It is created by the main superconductor. Usual range for clinical systems are 1.5T to 7T while for preclinical systems values of up to 20T have been reported.
 
```B1:``` The magnetic field B1 is produced by a coil (surface or volume) during the pulse application and it is applied perpendicular to the main magnetic field B0. It spatial distribution is affected by the operational frequency of the MR scanner, the electric properties of the sample and the samples geometry. It can be divided into two fields the B1- which described the sensitivity of the coil in the receive mode and the B1+ which is the filed created by a coil while applying an RF pulse. magnetic field.

```Birdcage Coil:``` A birdcage is a volume coil consisting of "legs", or rungs, that are connected by end rings. This is the most used volume coil, and it is mostly used to transmit the MR signal since it can produce a very homogenous B1+ field.

```Echo Time (TE):``` The amount of time between the RF excitation pulse and when the signal is recorded. Short echo time spectroscopy generally uses a TE of ~35 ms while long echo time TE is often ~144 ms.

```Flip Angle:``` The flip angle is the amount of rotation the magnetization experiences during the application of an RF pulse. It is usually expressed in degrees (ο). Commonly used flip angles are 90o and 180o. In reality, a flip angle is not uniform throughout an image. It is affected by the type of coil (surface vs volume), the used RF pulse shape (e.g. rectangular, Gaussian, sinc), as well as slice-selection gradients, and B0 field inhomogeneities. These effects become particularly problematic as field strengths are increased.

```Multi-channel:``` Multi-channel systems consist of multiple receivers that are available for each of the multiple coils in the system. These coils may correspond to coils used for different frequencies (i.e., multiple nuclei) or for those in a phased array system. Many head coils used in the clinic and in research are phased arrays.

```Field Strength:``` The strength of the primary magnetic field, B0, that is responsible for homogenizing or aligning the nuclear spins. As this magnetic field becomes stronger, it is able to homogenize or align a greater percentage of the nuclei, leading to more signal. Typical clinical MRI scanners have a strength of 1.5 Tesla (T). Newer scanners have higher field strengths of 3T. Some research scanners can have 7T or higher, but as of 2022, 7 T is the highest field strength approved for clinical use in some countries.

```Frequency Domain:``` Unlike the time domain, data in the frequency domain represents either a single time point or a fixed length of time. The units of the x-axis change from seconds to hertz. In spectroscopy, frequency domain signals or plots are called spectra and they represent the frequency of each sinusoid that comprise a given time domain signal. See also spectrum/spectra.

```Image-Selected In vivo Spectroscopy (ISIS):``` ISIS consists of two parts, preparation and acquisition. During the preparation, a small 180 pulse together with a gradient inverts the magnetization of a slice orthogonal to the axis of the applied gradient, because only in this slice the resonance condition is fulfilled (slice selective inversion). This is followed by the application of a non-selective 90 excitation pulse and signal acquisition. If the experiment is performed twice, once with and once without the selective inversion pulse and then the two signals are subtracted, we obtain a signal only from the magnetization of the inverted slice. For a 2D or 3D experiment, four or eight experiments respectively have to be performed. The sequence is mainly used for 31P spectroscopy, where metabolites of interest have short T2 values. As signal acquisition starts immediately after the 90 excitation that limits signal losses. Major limitations of ISIS is subtraction errors, due to signal contamination from previous pulses, and motion artifacts, due to the multiple excitation requirement.

```Localizer/Scout:``` The localizer is typically a low resolution, fast T1-weighted scan to identify the location and geometry of the object or patient being scanned. This is often used in MRS to set the saturation bands, to select the shimming region, and to select voxels for acquisition.

```Pixel:``` A pixel is a single data point in a 2D image. As the density of pixels increases, so does the spatial resolution of the image. 

```Point RESolved Spectroscopy (PRESS):``` PRESS is one of the most common methods used for in vivo 1H spectroscopy. The sequence consists of 3 slice selective pulses, a 90o followed by two 180o. The PRESS signal at the echo time is a spin echo and it originates only from protons that have experience all 3 pulses. These protons are located in a cube shaped voxel at the intersection of the 3 excited slices. A disadvantage of PRESS is the minimum achievable echo time, so metabolites with short T2 cannot be resolved (e.g. 31P). Another limitation is tissue heating due to multiple 180o pulses.

```Radiofrequency Pulse (RF):``` There are many types of pulses used in MRS. An ideal pulse is a square pulse. The RF pulse is the energy used to ‘excite’ the nuclear spins during the transmit step so they can be detected (see Transmit).

```Receice:``` The receive step of the NMR experiment consists of detecting the voltage induced on the receive coil because of the oscillating magnetic field generated by the spins. This signal goes through a chain of amplification, filtering, and other signal processing steps. The receive and transmit chains are separated through the transmit/receive switch.

```Region-of-interest (ROI):``` The ROI is a region of a spectra or image that is relevant to the given task at hand. For example, when performing phase and frequency shift corrections in proton spectroscopy, the ROI of the spectrum is often near the water peak at 4.68 ppm.

```Repetition Time (TR):``` The amount of time between the first excitation pulse and the subsequent excitation pulse. This period of time will include an excitation pulse followed by one or more echoes. Ideally, the TR should be sufficiently long such that T1 and T2 relaxation is complete or nearly complete before the next excitation. For spectroscopy, TR is often ~1-2 seconds.

```Shimming:``` Shimming is the process of correcting the inhomogeneities of the main magnetic field (B0). Shimming can be a passive or an active process. Passive shimming consists of adding ferromagnetic metals in specific locations within the magnet to compensate for the inhomogeneities. Active shimming is accomplished with shim coils that adjust the field in different directions, e.g., x, y, z, and it is user-controlled. Shimming can be automated by the MR scanner or ‘manual’ when adjusted by the user.

```Spectrometer:``` A spectrometer is responsible for measuring signal and detecting multiple frequencies. Colloquially, a spectrometer is the instrument that generates the excitation pulse and acquires the signal. In an MRI scanner, this piece of hardware can be used for localization (in imaging) or for signal detection in MR spectroscopy. An NMR spectrometer contains a similar piece of hardware.  

```STimulated Echo Acquisition Mode (STEAM):``` STEAM is another common method for in vivo H spectroscopy that uses three slice selective 90o pulses forming a stimulated echo after the total of the echo time (double the time between the first two pulses) and the mixing time (delay between 2nd and 3rd pulse). The signal at the stimulated echo originates only from protons that have experienced all 3 pulses. These protons are located in a cube shaped voxel at the intersection of the 3 excited slices. The method allows shorter echo times compare to PRESS but the signal intensity is only half for the same echo time. Also the usage of 90 pulses allows voxel localization with sharper edges and lower tissue energy deposition.

```Surface Coil:``` This coil is commonly designed as a circular loop, but it can also have other shapes. They are used for receiving the MR signal since they provide improved SNR over a small region. Surface coils are combined to make arrays and increase the field of view.

```T1:``` The longitudinal relaxation T1 (or spin-lattice relaxation) describes the return of the spin system to the magnetic equilibrium state and involves energy exchange with the environment. T1 can be viewed as the time required for the z-component of the magnetization to reach about 63% (=1-1/e) of its maximum value. For biological tissue, proton relaxation times are typically of the order of a few tenth of a second to several seconds and depend on the magnetic field strength. 
 
```T2:``` The transverse relaxation time T2 (or spin-spin relaxation) is the process by which the transverse components of magnetization decay or diphase. It involves the loss of the phase coherence between nucleus precession in the transverse plane. As a results the net magnetization decreases as a function of time. It is the time required for the transverse magnetization to fall to approximately 37% (=1/e) of its initial value. 
 
```T2*:``` Additional to the T2 relaxation time there are additional mechanism leading to loss of phase coherence. The spatial variations in the strength of the magnetic field within the body either due to the intrinsic magnet design which does not produce a perfectly uniform magnetic field over the entire object and due to the different magnetic susceptibilities of different tissues (mainly pronounced at air/tissue and bone/tissue boundaries). Together all these mechanisms account for the relaxation time T2*.

```Time domain:``` The time domain is an information domain in which data is expressed as a function of time. In spectroscopy, the signal is collected by the instrument in the time domain. A free induction decay is an example of a time domain signal in spectroscopy. Other examples of time domain signals include voice recordings, ECGs, weather forecasts, and stock market trackings.

```Transients:``` Also known as averages, transients determine the number of times the NMR experiment is repeated. For in vivo spectroscopy, the experiment needs to be repeated many times to generate sufficient signal.

```Transmit:``` The transmit step of the NMR experiment consists of exciting nuclei using a time-varying magnetic field (B1). This field is produced by a transmit coil tuned to the Larmor frequency.

```Volume-of-interest (VOI):``` Similar to the ROI, the VOI is the region of interest in an imaging volume. In brain spectroscopy, this could be e.g., a physiological structure or a pathological tumor.

```Voxel:``` A voxel, much like a pixel, is a single data point that represents a volume. MR images are presented as 2D images or stacks of 2D images; however, they actually represent a 3D volume in space. In multi-voxel MRS (MRS imaging or MRSI), voxels are often isometric or isotropic, i.e., a cube with equal sides.

```Water Suppression:``` A challenge with 1H spectroscopy is that the signals coming from different molecules are usually overwhelmed by the water signal. As a result, there are pulse sequences that can be used to suppress the water signal, which allows other signals/peaks to be visible in the spectrum.


## Pre-processing 

```Apodization:``` Apodization is a way to smooth some of the noise in order to improve the SNR. This is done by multiplying the FID by a negative exponential function. This is analogous to applying a low-pass filter to the data. This works because noise typically occurs in the higher frequency ranges. Even though this improves the SNR, it has the undesirable effect of line broadening. Line broadening not only widens the metabolite peaks in the frequency domain, it also lowers their peak heights. Therefore, this should not be used in combination with analysis methods that use a linear combination model.

```First-order phase correction:``` First-order phase, also known as linear phase, is frequency-dependent. Typically, the water peak at 4.68 ppm is used as the reference point for correcting this offset. First-order phase can be apparent when evaluating the shape of the metabolite peaks. The larger the phase offset, the more asymmetrical the peaks become with the side furthest from the reference point developing more and more severe tails. 

```Frequency Shift:``` Frequency shift is the phenomenon of metabolite peaks being shifted left or right in the frequency domain. This can be caused by things like temperature differences, subject motion during acquisition, and changes in pH. Correcting these shifts (which can lead to errors in quantification) can be challenging in in vivo spectroscopy because external references are not commonly used as standards to determine the correction. In proton MRS, the water peak is typically used. Fitting algorithms often allow for small tolerances, ±20Hz, for each metabolite, which for 3T spectra is about 0.05 ppm.

```Line Shapes:``` For spectroscopy data, there are three line shape profiles that describe the spectral peaks: Lorentzian, Gaussian, and Voigt. 

	**- Lorentzian Line Shapes:** These are generally rather narrow line shapes. This means that their full-width half-maximum is generally small. While being narrow is desirable, they also decay rather quickly through time. The Lorentzian term is defined as exp(+t/T2*).

	**- Gaussian Line Shapes:** These peaks tend to be broader than Lorentzian peaks, but decay more slowly. This term is defined as exp(-t2/TG2).

	**- Voigt Line Shapes:** Voigt line shapes combine the Lorentzian and Gaussian terms to create a more realistic line shape that is still narrow and maintains a long decay time.

```Peak Shape:``` Peak shapes are described by position (generally ppm), maximum height (indicative of their concentration), and their full-width half-maximum. Relative concentrations are calculated by quantifying the maximum height or the area under the peak. These values are then compared to a stable reference that is also present in the signal.

```Phase correction:``` All MRI measurements produce complex data (that contains real and imaginary components). In spectroscopy, the real component of the spectrum needs to be in “pure absorption” mode to produce accurate quantification results. There are two types of phase offsets that need to be corrected: zero-order and first-order. The result of phase correction should lead to all peaks in the spectrum pointing upwards such that the peaks are relatively symmetric. 

```Pre-processing:``` a series of steps taken to improve the quality of the acquired spectra, prior to quantifying concentration or other parameters of interest (e.g., pH). Depending on the expected use of the processed spectra, not all pre-processing steps may be appropriate. Steps may include coil combination, phase correction, frequency shift correction, zero-filling, apodization, and baseline removal. Some steps may be performed automatically by the MRI scanner or software.

```Zero-filling:``` adding zeros to the end of the FID in order to (artificially) increase the spectral resolution after the Fourier Transform. 

```Zero-order Phase Correction:``` Zero-order phase affects the entire spectrum uniformly. The basic objective functions used to correct this phase offset include maximizing the area under the real component while minimizing the area under the imaginary component. Several methods exist but many software tools can do this step automatically.

## Analysis 

```Basis Set:``` When simulating or fitting spectra, it is common to use a set of ideally simulated spectra for the given echo time, scanner brand (e.g., GE, Siemens, Philips), and metabolite. A simulated spectrum for an individual metabolite is called a basis line and a collection of these basis lines is known as a basis set. The final spectrum can then be fit using a linear combination of the basis set.

```Cramer-Rao Lower Bounds (CRLB):``` They express the lower threshold of the error associated with a model fitting. The evaluation tool LCModel is one of the most common tools providing such values with every spectral analysis. 

```Fourier Transform:``` The Fourier transform is a technique used to transform data between the time and frequency domains. In NMR, the Fourier transform enables the conversion of the time-varying signal, also known as Free Induction Decay (FID), into spectral peak(s).

```Full-width Half-maximum (FWHM):``` The width of a spectral peak (in the frequency domain) at half of the peak's maximum height. This value is commonly used as a measure of the peak's resolution. Generally, narrower peak width is better.

```Residual:``` When fitting a spectrum, a series of parameters are used to convert a standard basis set into a spectrum that matches the input (original) spectrum. The residual is what is left after the fitted spectrum is subtracted from the input spectrum. The input data is generally noisy while the fit is noise-free, therefore, a good fit should result in a residual that looks like pure Gaussian noise (mean signal = 0). As the quality of the fit declines, larger and more noticeable artifacts appear in the residual. If clear peaks appear in the residual, this is generally a sign of poor spectral fitting.

```Peak Area (Amplitude):``` See Peak Integration. The area under a peak is obtained through peak integration and it is a measure of its intensity and the relative concentration of the NMR nucleus. Usually, peak area is used to refer to a peak in the frequency domain. The signal amplitude often refers to the signal in the time domain (where there are no peaks).

```Peak Fitting:``` Peak fitting enables the quantification of MRS spectra. When fitting a peak, the shape and height of the peak are approximated as closely as possible using a fitting algorithm.

```Peak Integration:``` Peak integration is used to determine the area under the peak. The area provides an estimate for the peak intensity, as well as the relative concentration of the nucleus being studied.

## Additional MRI Glossaries

```Expert Consensus on Terms in MRS``` [Link](https://analyticalsciencejournals.onlinelibrary.wiley.com/doi/full/10.1002/nbm.4347)  

```Simple``` [Link](https://onlinelibrary.wiley.com/doi/pdf/10.1002/9781118782934.gloss)

```Comprehensive```[Link](https://www.acr.org/-/media/ACR/Files/Radiology-Safety/MR-Safety/MRGlossary.pdf)

